version: "3.8"

services:
  arcadia-stats-api:
    ports:
      - "4"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  arcadia-stats-spa:
    ports:
      - "4200:4200"
    build:
      args:
        ENV: docker