version: "3.8"

services:
  arcadia-stats-api:
    ports:
      - "5000:5000"
      - "5001:5001"
    image: ${DOCKER_REGISTRY-}arcadia-stats-api
    container_name: "arcadia-stats-api"
    build:
      context: ../src/
      dockerfile: WebUI/Dockerfile
    volumes:
      - ~/.aspnet/https:/https:ro
    environment:
      - "UseInMemoryDatabase=false"
      - "ConnectionStrings__DefaultConnection=Server=db;Database=CleanArchitectureDb;User=sa;Password=Your_password123;MultipleActiveResultSets=true"
      - "IdentityServer__Key__Type=Development"
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=Your_password123"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - "SA_PASSWORD=Your_password123"
      - "ACCEPT_EULA=Y" 
